### ISSUE TITLE
Create License for package

### ISSUE THREAD

**Issue by rudresh4** [rudresh4/patchwork#56]
- Make sure no one can copy repository code by creating License for package

**Comment by hsdistefa** [comment]
Did some research:

- Copyright is implicit, but it is recommended to put a header at the top of each source file e.g. 

`/* Copyright (C) 2017 Rudresh Amin - All Rights Reserved
 * You may use, distribute and modify this code under the
 * terms of the XYZ license
 *
 * You should have received a copy of the XYZ license with
 * this file. If not, please write to: , or visit :
 */`

- Licensing is releasing *full* control with explicit usage rights given to users of the software and is much more complex. Should discuss this along with the business model

**Comment by rudresh4** [comment]
I think it's fine for now until we get paying customers.
