### ISSUE TITLE
Couldn't find file 'bootstrap-select' with type 'text/css'

### ISSUE THREAD

**Issue by hsdistefa** [rudresh4/patchwork#57]
Trying to setup on my computer. Ubuntu 14.04
-Ran bundle install
-rails server
-localhost:3000 in browser

![screenshot from 2017-11-14 13 45 47](https://user-images.githubusercontent.com/5913237/32806741-7cf20ca8-c942-11e7-965b-dcd78bb4f53b.png)

**Comment by rudresh4** [comment]
Follow the setup guide to install, build, and run project:

https://github.com/rudresh4/patchwork/wiki/Setup
